import './globals.css';
import Navbar from '../components/navbar';

export const metadata = {
  title: {
    absolute : "",
    default: 'Hello, World!',
    template: '%s | Next.js',
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        {children}
        </body>
    </html>
  )
}
